* Justin Knox, B.Sc., CC
2232 S Main St. #292, Ann Arbor MI, 48103 | M: 313.466.2808
--------
#+OPTIONS: toc:nil
#+OPTIONS: num:nil
#+GEOMETRY: margin=1.5cm
#+LATEX_COMPILER: xelatex
#+LATEX_CLASS_OPTIONS: [letter,10pt]
#+LATEX_HEADER: \usepackage[T1]{fontenc}
#+LATEX_HEADER: \renewcommand*\oldstylenums[1]{{\fontfamily{Montserrat-TOsF}\selectfont #1}}
#+LATEX_HEADER_EXTRA: \usepackage{fontspec}
#+LATEX_HEADER_EXTRA: \setmainfont{FreeMono}
#+LATEX_HEADER: \usepackage[margin=1.5cm]{geometry}
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage{graphicx}
#+ATTR_HTML: width="100px"
#+ATTR_ORG: :width 100
#+ATTR_LATEX: :width 100
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \hypersetup{ colorlinks, urlcolor={blue!80!black!} }
[[mailto:justin.knox@posteo.de][justin.knox@posteo.de]] | [[https://www.linkedin.com/in/justintknox][linkedin.com/in/justintknox]] | [[https://www.github.com/jknoxdev][@github.com/jknoxdev]] \\
[[https://gitlab.com/n1ghtcr3w][@gitlab.com/n1ghtcr3w]] | [[https://matrix.to/#/@techbiotic:matrix.org][@techbiotic:matrix.org]]


* Objective:              Systems Administrator
* Experience:
#+begin_src latex :results output raw
 \begin{wrapfigure}{l}{0.25\textwidth}
 \includegraphics[width=0.45\linewidth]{./img/50p_cr_utk.jpg}
 \end{wrapfigure}
 #+end_src
** University of Tennessee, Knoxville | Graduate Student
*** Studying for Masters of Science in Computer Science | Online, Ann Arbor, MI | Dec 2022 - Present
 - Specialization is in Data Science & Intelligent Systems; with Dual-Major in Software Engineering.
#+begin_src latex :results output raw
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/jpeg_banner.jpg}
\end{wrapfigure}
#+end_src

** jPegDesign | Technical Specialist II
*** Camera, IT & Network Systems Design, Deployment & Support | Ann Arbor, MI | March 2023 – Present
**** Provide managed IT services covering all aspects of SMB IT including Active Directory GPOs, Windows AD servers, Access Control, POS, VOIP, Network & Cloud Infrastructure.
**** Technologies include VOIP, Biometric & RFID Access Control Systems (with door stikes), CAT6 & Fiber networking, Wireless Access points, backhaul repeaters, Wireless (CDMA, LTE & MIMO) antennas, IP Cameras & NVR systems.
**** Provide installation, support & configuration for any type of SMB infrastructure & appliances; including, servers, network infrasturcture, structured cabling, access controls, cameras, monitoring and alarm systems.
**** Main clients are primarily in the hospitality & retail industries.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_alchemy_computing.jpg}
\end{wrapfigure}
#+end_src

** Alchemy Computing | Freelance Technical Consultant
*** Fullstack Development, Systems Architecture & Design | Ann Arbor, MI | Dec 2021 – Present
**** Services include, small business infrastructure design, development & deployment, full-stack development, wireless network design and server disaster recovery.
**** Notable clients are primarily in the legal, entertainment and construction industries.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.85\linewidth]{./img/cr_google.jpg}
\end{wrapfigure}
#+end_src
** Google | Operations Engineer II / DT3
*** Global & 3^rd Party Datacenter, Engineering Field Services, Hardware, Network & Server Operations | Charleston, SC; Reston, VA | Dec 2018 – Dec 2021
   - Developed a suite of scripts for automation to aid in fleet deployment, maintenance and fault resolution covering the approx 1/3 of the east-coasts' Google fleet. Languages used included Python, Ruby, JavaScript/ECMAScript, BASH, BASH, HTML & Javascript  on the global CI/CD (internal) github.
   - Provisioned Active Directory and GPO accounts for biometric, RFID, and physical access systems contained in the 3rd party datacenters and edge portion of the fleet.
   - Provided engineering field services of deployment, configuration and troubleshooting of Google servers, network and infrastructure devices.
   - Deployed, maintained and configured the internal rack security units as well as external physical perimeter protection devices.
   - Received 19 Peer Bonuses, and 2 Awards for Hurricane & Pandemic Support.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_cr_switch.jpg}
\end{wrapfigure}
#+end_src
** Switch LTD | Datacenter Technician
*** Network Operations | Las Vegas, Nevada | July 2017 - Dec 2018
  - Deployed customer network configurations from schematic to configuration, utilizing a wide variety of industry vendors including Cisco, Juniper, Cienna, Palo-Alto, Dell, HP, Checkmate, Alcatel-Lucent as well as other proprietary equipment.
  - Provided network incident detection in the internal Network Operations Center and issue escalation, for outages on customer nodes as well as production upstream links.
  - Coordinated with Engineering teams from over 2,300 customer deployments to provide regional technical support issues on customer provided infrastructure ranging on deployments that ranged from 1RU, to multi-campus / LAN and multi-sector-wide / WAN deployments.
  - Ensured perimeter security and conducted routine production infrastructure security audits in compliance with customer provided ISO specifications.
#+begin_src latex :results output raw
\\
\\
#+end_src


#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_cr_pinnacle.jpg}
\end{wrapfigure}
#+end_src
** Pinnacle Community Services | IT Support Technician IV
*** Information Technology | Las Vegas, Nevada | Oct 2016 - June 2017
  - Designed, built and migrated the company back-end infrastructure over to HIPAA compliant, open source and license free solutions.• Implemented strategy to acquire ISO 27001 compliance for the internal datacenter.
  - Provided systems administration, network design, deployment and support for the Nevada region covering 30 remote locations and three office campuses; in a mixed Windows Server 2016, RedHat, OpenSuse, FreeBSD and Ubuntu environment.
  - Conducted forensic investigations to procure data for human resource and legal departments utilizing Autopsy, the Sleuth toolkit, PhotoRec and self-developed Log analysis software.
  - Modified and secured the Active Directory Group Policy Objects (GPO) of the production network to properly reflect and align with organizational restructuring.
  - Created and migrated the data storage servers to fully encrypted internal storage at rest and in transit.
  - Created the secondary backup file servers and using best practices; security hardened the BSD platform.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_cr_scientific_games.jpg}
\end{wrapfigure}
#+end_src
** Scientific Games | Technical Specialist II
*** Technical Training & Documentation | Las Vegas, Nevada | Nov 2013 - April 2015
  - Managed and created the company’s internal training database utilizing SQL on a MySQL deployment; and implemented it into its eventual migration to the production Office 365 SharePoint servers.
  - Designed and built the mem-cached Arch Linux prototype server infrastructure to distribute the in-house training videos out via the company WAN.
  - Interfaced with Hardware & Software Engineering teams to develop internal training to distribute to ~680 technicians globally on a monthly release cycle.
  - Designed, developed and built the companies first Casino training laboratory. This mirrored the in-field deployment for the entire product line of gaming machines and networks.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_alchemy_computing.jpg}
\end{wrapfigure}
#+end_src
** Alchemy Computing | Freelance Technical Consultant
*** Web Development, Computer Repair, Electronics Prototyping | Los Angeles, CA | Sept 2009 – Nov 2013
  - Services included, small business desktop and infrastructure support, web development and design, electronics product prototyping development, wireless penetration testing, data recovery, forensic analysis, wireless network design and server disaster recovery.
  - Notable clients were primarily in the legal, entertainment and cosmetic industries.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_cr_bt.jpg}
\end{wrapfigure}
#+end_src
** British Telecom | Network Event Management Technician III
*** Global Operations Tier 3, Converged Services Management Center | El Segundo, California | May 2008 - Sept 2009
  - Created and deployed the workstation images used for the NOC, assisted in the consolidation of software used from 12 different teams into one.
  - Provided Tier 3 support, including the provisioning, maintenance and performance monitoring of BT-Infonet’s internet backbone; in a cross-platform; mixed vendor environment; platforms included Cisco, Alcatel Lucent, Juniper & Cienna based equipment.
  - Protocols included: MPLS, EIGRP, IGRP, Frame-Relay, TCP/IP V4/V6, SIP, ARP, CDP, EIGRP, OSPF, BGP, VTP, Etherchannel, 802.1Q trunking, QoS, Multicast, 802.11a/b/g/n/ac, IPSec, LDAP, RADIUS/TACACS+, SNMP, NTP, VRF and HTTP/HTTPS.
  - Designed, developed and implemented a computer vision application utilizing the OpenCV API to notify technicians of network alarm status.
#+begin_src latex :results output raw
\\
\\
#+end_src

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_cr_synetcom.jpg}
\end{wrapfigure}
#+end_src
** Synetcom Digital | Junior Electronics Engineer
*** Torrance, California | June 2006 - Nov 2007
  - Developed and implemented IPSec on the Active Directory LAN intranet and secured it in a mixed windows Linux development environment.
  - Designed and converted existing customer networks to support fail over resistant mesh network topology utilizing FHSS (frequency hopping spread spectrum) radios.
  - Conducted Wireshark traffic and packet analysis to help secure and harden SCADA radio networks in point-to-point, star, bus and wireless mesh topologies.
  - Developed and implemented software utilizing the embedded System on Chip encryption modules with AES256 to secure video over radio communications.
  - Utilized Kismet, Spectrum analyzers and custom built software to conduct wireless penetration testing to ensure communication security.
  - Worked in the engineering team developing industrial SCADA radios for monitoring digital IO, 4-20ma sensor loops, PWM, and industrial video applications.
  - Designed, conducted and implemented quality assurance and field simulation testing for complete product range.
  - Created laboratory experiments to emulate exhibited field errors and develop for more solutions to solve them.
  - Researched and integrated emerging technologies into new products for field deployment.

#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0.25\textwidth}
\includegraphics[width=0.8\linewidth]{./img/50p_cr_devry.jpg}
\end{wrapfigure}
#+end_src
** DeVry University | Computer & Electronics Laboratory Work-Study, & Tutor
*** Office of Academic Support and Instruction Services, Advanced Development Laboratory, Network Laboratory, Computer Laboratory, Electronics Laboratory | Long Beach, California | Mar 2004 - June 2006
 - Worked closely with the IT department on campus to roll-out user profiles, administer accounts to new users, assist faculty with technical issues, and provide off hours support, deployment & reconfigurations for campus infrasturcture.
 - Technologies used included Novel, Windows XP - 2000 - 7, Windows Server IIS, Gentoo Linux, Active Directory, MatLab, SPICE, Cisco Routers and switches, UNIX & Tape backup systems, Network Cat2, Cat5-5e deployment, RS-232 & 485.
#+begin_src latex :results output raw
\begin{wrapfigure}{l}{0\textwidth}
\includegraphics[width=0.0\linewidth]{}
\end{wrapfigure}
#+end_src


* Technical Skills & Security Tools:
** Vulnerability Assessment Tools:
Nmap, Net Stumbler, Netcat, Kismet, Wireshark, Kali Linux, Pentoo Linux
** Languages:
C, C++, Java, SQL, BASH, LaTeX, YACC, YAML, XML, HTML, CSS, JavaScript, Ruby, Python, Assembly
** Cloud / Server / HyperVisor Operating Systems:
Windows 10, Windows 2016, RHEL 7, Macintosh OSX, SUSE Linux, Ubuntu, Debian, Gentoo, VMWare, ESXi, OpenBSD, FreeBSD, NetBSD, Docker, XCP-NG, EVE-NG, VirtualBox
** Applications:
Office, Sharepoint, Adobe Premiere, Adobe After Effects, Adobe Photoshop, Adobe Illustrator, MATLab, Slicer (3D Printing)
** Databases:
PostreSQL, MS SQL Server 2008, MS Access, MySQL
* Education:
** Graduate Student, Master of Science in Computer Science
University of Tennessee, Knoxville, Dec 2022 - Present
** Web Development Full Stack Bootcamp
LeWagon, Rio de Janeiro, Brazil, June 2021 – Sep 2021
** Bachelor of Science, Computer Engineering Technology
DeVry University, Long Beach, California, Oct 2003 – March 2008
GPA: 3.58, Summa Cum Laude, Academic Honors: Dean’s List, 2003 - 2007

* Certificates:
** (ISC)² Certified in Cybersecurity / CC
International Information System Security Certification Consortium (ISC)²
Active as of: September 2022
